# Generated by Django 4.0.3 on 2022-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_school_alter_class_teachers'),
        ('student', '0003_student_order_in_class_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentExel',
            new_name='StudentExcel',
        ),
    ]
