# Generated by Django 4.0.3 on 2022-05-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_studentexel_studentexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExcel',
        ),
    ]
