# Generated by Django 4.0.3 on 2022-05-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_school_alter_class_teachers'),
        ('student', '0005_delete_studentexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='origin_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.class'),
        ),
    ]
